services:
  postgres:
    image: postgres:14
    container_name: reservation_db
    environment:
      POSTGRES_DB: reservation_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_network
  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "3000" # Expose frontend on port 3000
  #   networks:
  #     - backend_network

  python-web:
    build: ./backend/python
    volumes:
      - ./backend/python:/src
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - backend_network

  go-api:
    build: ./backend/goAPI
    volumes:
      - ./backend/goAPI:/src
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - backend_network

volumes:
  postgres_data:


networks:
  backend_network:
    driver: bridge
