version: '3'
services:
  postgres:
    image: postgres:14
    container_name: reservation_db
    environment:
      POSTGRES_DB: reservation_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_network
   
#  python-web:
#    build: ./python
#    command: python manage.py runserver 0.0.0.0:8000
#    volumes:
#      - .:/src
#    ports:
#      - "8001:8000"
#    depends_on:
#      - postgres
#    networks:
#      - backend_network

volumes:
  postgres_data:

networks:
  backend_network:
    driver: bridge