# This workflow will build a Golang project only when files in goAPI change

name: Go

on:
  push:
    branches: [ "master" ]
    paths:
      - 'backend/goAPI/**'  # Only trigger when files in goAPI change
  pull_request:
    branches: [ "master" ]
    paths:
      - 'backend/goAPI/**'  # Only trigger when files in goAPI change

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.6'
    
    - name: Run tests
      run: go test -v ./test
      working-directory: ./backend/goAPI
